# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ErIzlPt9H5Sy4LYh5-QSHC5fJ7L_m1_6
"""

from catboost import CatBoostClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
import pickle
import sys
import numpy as np
import pandas as pd
import argparse


def create_df(df):
    # Filtrar las filas del carrier y seleccionar las columnas necesarias
    df2 = df[['SCHEDULED_DEPARTURE','SCHEDULED_ARRIVAL',
                'ORIGIN_AIRPORT','DESTINATION_AIRPORT','DEPARTURE_DELAY','AIRLINE']]
    df2.dropna(how='any', inplace=True)
    # Convertir las columnas de fecha a datetime
    df2['SCHEDULED_DEPARTURE'] = pd.to_datetime(df2['SCHEDULED_DEPARTURE'])
    df2['SCHEDULED_ARRIVAL'] = pd.to_datetime(df2['SCHEDULED_ARRIVAL'])

    # Añadir columna con el día de la semana
    df2['weekday'] = df2['SCHEDULED_DEPARTURE'].apply(lambda x: x.weekday())

    # Convertir retrasos en una clasificación binaria (0: no retraso, 1: retraso >= 15 minutos)
    df2['DELAY_CLASS'] = df2['DEPARTURE_DELAY'].apply(lambda x: 1 if x >= 15 else 0)

    # Convertir las horas a segundos
    fct = lambda x: x.hour*3600 + x.minute*60 + x.second
    df2['heure_depart'] = df2['SCHEDULED_DEPARTURE'].apply(lambda x: fct(x.time()) if isinstance(x, pd.Timestamp) else None)
    df2['heure_arrivee'] = df2['SCHEDULED_ARRIVAL'].apply(lambda x: fct(x.time()) if isinstance(x, pd.Timestamp) else None)

    return df2


# Configurar argparse para recibir el archivo CSV y el carrier
parser = argparse.ArgumentParser(description="Entrenamiento de modelo CatBoost para predicción de retrasos.")
parser.add_argument("csv_file", type=str, help="Ruta al archivo CSV con los datos de entrenamiento")

# Parsear los argumentos
args = parser.parse_args()

# Preprocesamiento del dataframe
df3 = create_df(pd.read_csv(args.csv_file))

# Codificación de la columna categórica 'ORIGIN_AIRPORT'
label_encoder_airport  = LabelEncoder()
df3['ORIGIN_AIRPORT_ENC'] = label_encoder_airport .fit_transform(df3['ORIGIN_AIRPORT'])
label_encoder_airline = LabelEncoder()
df3['AIRLINE_ENC'] = label_encoder_airline.fit_transform(df3['AIRLINE'])

# Codificación one-hot de 'ORIGIN_AIRPORT_ENC'
onehot_encoder_airport  = OneHotEncoder(sparse_output=False)
onehot_encoder_airline  = OneHotEncoder(sparse_output=False)  # Cambiado 'sparse' a 'sparse_output'
airport_encoded = onehot_encoder_airport.fit_transform(df3[['ORIGIN_AIRPORT_ENC']])
airline_encoded = onehot_encoder_airline.fit_transform(df3[['AIRLINE_ENC']])


# Preparación de los datos para el modelo
X = np.hstack((airport_encoded, df3[['heure_depart', 'heure_arrivee', 'weekday']].values))
Y = df3['DELAY_CLASS'].values  # Usamos la columna binaria DELAY_CLASS como objetivo

# Dividir los datos en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Crear el modelo CatBoostClassifier
catboost_model = CatBoostClassifier(iterations=1000, learning_rate=0.1, depth=6, verbose=100)

# Entrenar el modelo
catboost_model.fit(X_train, y_train)

# Guardar el modelo entrenado en un archivo
with open('modelo_entrenado.pkl', 'wb') as f:
    pickle.dump(catboost_model, f)

with open('label_encoder_airport.pkl', 'wb') as f:
    pickle.dump(label_encoder_airport, f)
with open('label_encoder_airline.pkl', 'wb') as f:
    pickle.dump(label_encoder_airline, f)
with open('onehot_encoder_airport.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_airport, f)

#model_features = catboost_model.feature_names_
#print(model_features)
#print("catboost_model.feature_names_: ", catboost_model.feature_names_)
#print("COLUMNS TYPE TRAIN: ", df3.dtypes)
print("Modelo entrenado con CatBoost y guardado como modelo_entrenado.pkl")